### PR TITLE
FernoConfiguration.tokenExpirationDate typo fixed

### PR DESCRIPTION
**Pull request by chibombo**
## What changed

- Typo error: `FernoConfiguration.tokenExpriationDate` to `FernoConfiguration.tokenExpirationDate`

✅ Tests passed ✅

Screenshot 2023-10-05 at 9 51 34 PM

### CODE REVIEW

**Comment by 0xTim** [comment]
@chibombo do you fancy setting up CI with GH actions so we catch this in the future?

**Comment by chibombo** [comment]
Sure, no problem, Do you have a favorite GH action for this? 👀

**Comment by 0xTim** [comment]
Tbh just running `swift test` on a Ubuntu runner is probably fine!

**Comment by chibombo** [comment]
I'm working on another PR where we can inject the FirebaseJson to set up the Ferno configuration. I'll add some new tests. TBH It could be complicated to have a good coverage of this, considering that the current test implementation required a real Firebase connection, and we will need an account to hardcode the connection. 

I suggest merging this, and in the other PR I can add more tests that don't need the connection to the real Firebase database and in the GH action, indicate that only run those new tests. 

What do you think?

**Comment by 0xTim** [comment]
Fine by me

**Pull request merged**
